/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen1p2_edgarmembren;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author edgarmembreno
 */
public class LOGIN extends javax.swing.JFrame {

    /**
     * Creates new form LOGIN
     */
    public LOGIN() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_CrearUsario = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tf_nombreUsuario = new javax.swing.JTextField();
        tf_ApellidoUsuario = new javax.swing.JTextField();
        tf_CorreoUsuario = new javax.swing.JTextField();
        tf_NumeroUsuario = new javax.swing.JTextField();
        Individual = new javax.swing.JRadioButton();
        familiar = new javax.swing.JRadioButton();
        tf_User = new javax.swing.JTextField();
        tf_Pass = new javax.swing.JTextField();
        boton_CrearUsuario = new javax.swing.JButton();
        jDialog2 = new javax.swing.JDialog();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        user_login = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pass_login = new javax.swing.JTextField();
        login_button = new javax.swing.JButton();
        crear_CuentaBoton = new javax.swing.JButton();

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel3.setText("Crear Usuario");

        jLabel4.setText("Nombre");

        jLabel5.setText("Apellido");

        jLabel6.setText("Correo");

        jLabel7.setText("Numero");

        jLabel8.setText("Plan");

        jLabel9.setText("User");

        jLabel10.setText("Pass");

        buttonGroup1.add(Individual);
        Individual.setText("Individual");

        buttonGroup1.add(familiar);
        familiar.setText("Familiar");

        boton_CrearUsuario.setText("Crear");
        boton_CrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_CrearUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_CrearUsarioLayout = new javax.swing.GroupLayout(jd_CrearUsario.getContentPane());
        jd_CrearUsario.getContentPane().setLayout(jd_CrearUsarioLayout);
        jd_CrearUsarioLayout.setHorizontalGroup(
            jd_CrearUsarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CrearUsarioLayout.createSequentialGroup()
                .addGroup(jd_CrearUsarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_CrearUsarioLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(jd_CrearUsarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(jd_CrearUsarioLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jd_CrearUsarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addGroup(jd_CrearUsarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(boton_CrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jd_CrearUsarioLayout.createSequentialGroup()
                                            .addGroup(jd_CrearUsarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(jd_CrearUsarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel4)
                                                    .addComponent(jLabel5)
                                                    .addComponent(jLabel6)
                                                    .addComponent(jLabel7))
                                                .addGroup(jd_CrearUsarioLayout.createSequentialGroup()
                                                    .addComponent(jLabel8)
                                                    .addGap(26, 26, 26)))
                                            .addGroup(jd_CrearUsarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jd_CrearUsarioLayout.createSequentialGroup()
                                                    .addGap(127, 127, 127)
                                                    .addGroup(jd_CrearUsarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(tf_NumeroUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                                        .addComponent(tf_CorreoUsuario)
                                                        .addComponent(tf_ApellidoUsuario)
                                                        .addComponent(tf_nombreUsuario)))
                                                .addGroup(jd_CrearUsarioLayout.createSequentialGroup()
                                                    .addGap(115, 115, 115)
                                                    .addGroup(jd_CrearUsarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(Individual)
                                                        .addComponent(tf_Pass, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(tf_User, javax.swing.GroupLayout.Alignment.LEADING))
                                                    .addGap(39, 39, 39)
                                                    .addComponent(familiar)))))))))
                    .addGroup(jd_CrearUsarioLayout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(jLabel3)))
                .addContainerGap(214, Short.MAX_VALUE))
        );
        jd_CrearUsarioLayout.setVerticalGroup(
            jd_CrearUsarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CrearUsarioLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel3)
                .addGap(38, 38, 38)
                .addGroup(jd_CrearUsarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_nombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_CrearUsarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_ApellidoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_CrearUsarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(tf_CorreoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_CrearUsarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(tf_NumeroUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jd_CrearUsarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Individual)
                    .addComponent(familiar)
                    .addComponent(jLabel8))
                .addGap(28, 28, 28)
                .addGroup(jd_CrearUsarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tf_User, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jd_CrearUsarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tf_Pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(boton_CrearUsuario)
                .addGap(109, 109, 109))
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Username:");

        jLabel2.setText("Password:");

        login_button.setText("Login");
        login_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_buttonActionPerformed(evt);
            }
        });

        crear_CuentaBoton.setText("Crear Cuenta");
        crear_CuentaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crear_CuentaBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(343, 343, 343)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(login_button, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                            .addComponent(crear_CuentaBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(55, 55, 55)
                                .addComponent(pass_login, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(user_login, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(user_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pass_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(login_button)
                .addGap(18, 18, 18)
                .addComponent(crear_CuentaBoton)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void login_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_buttonActionPerformed
        try {
            String username = user_login.getText();
            String password = pass_login.getText();
            if (username.equals("admin") && password.equals("1234")) {

            } else {
                JOptionPane.showMessageDialog(this, "** USUARIO INCORRECTO **");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "** OCURRIO UN ERROR **");
        }
    }//GEN-LAST:event_login_buttonActionPerformed

    private void boton_CrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_CrearUsuarioActionPerformed

        String nombre = tf_NumeroUsuario.getText();
        String apellido = tf_ApellidoUsuario.getText();
        String correo = tf_CorreoUsuario.getText();
        String numero = tf_nombreUsuario.getText();
        String plan = "";
        if (familiar.isSelected()) {
            plan.equals("Familiar");
        } else if (Individual.isSelected()) {
            plan.equals("Individual");
        }
        String user = tf_User.getText();
        String pass = tf_Pass.getText();
        
        
        tf_NumeroUsuario.setText("");
        tf_ApellidoUsuario.setText("");
        tf_CorreoUsuario.setText("");
        tf_nombreUsuario.setText("");
        tf_User.setText("");
        tf_Pass.setText("");
        
        usuario.add(new Usuarios(nombre, apellido, correo, numero, plan, user, pass));
        


    }//GEN-LAST:event_boton_CrearUsuarioActionPerformed

    private void crear_CuentaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crear_CuentaBotonActionPerformed

        jd_CrearUsario.setModal(true);
        jd_CrearUsario.pack();
        jd_CrearUsario.setLocationRelativeTo(this);
        jd_CrearUsario.setVisible(true);
    }//GEN-LAST:event_crear_CuentaBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOGIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Individual;
    private javax.swing.JButton boton_CrearUsuario;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton crear_CuentaBoton;
    private javax.swing.JRadioButton familiar;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JDialog jd_CrearUsario;
    private javax.swing.JButton login_button;
    private javax.swing.JTextField pass_login;
    private javax.swing.JTextField tf_ApellidoUsuario;
    private javax.swing.JTextField tf_CorreoUsuario;
    private javax.swing.JTextField tf_NumeroUsuario;
    private javax.swing.JTextField tf_Pass;
    private javax.swing.JTextField tf_User;
    private javax.swing.JTextField tf_nombreUsuario;
    private javax.swing.JTextField user_login;
    // End of variables declaration//GEN-END:variables
 ArrayList<Usuarios> usuario = new ArrayList();

}
