/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen1p2_edgarmembren;

import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author edgarmembreno
 */
public class LOGIN extends javax.swing.JFrame {

    /**
     * Creates new form LOGIN
     */
    public LOGIN() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_CrearUsario = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tf_nombreUsuario = new javax.swing.JTextField();
        tf_ApellidoUsuario = new javax.swing.JTextField();
        tf_CorreoUsuario = new javax.swing.JTextField();
        tf_NumeroUsuario = new javax.swing.JTextField();
        Individual = new javax.swing.JRadioButton();
        familiar = new javax.swing.JRadioButton();
        tf_User = new javax.swing.JTextField();
        tf_Pass = new javax.swing.JTextField();
        boton_CrearUsuario = new javax.swing.JButton();
        jd_admin = new javax.swing.JDialog();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        cb_servicio = new javax.swing.JComboBox<>();
        modificar_Usuario = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        tf_nombreServicioM = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        tf_precioServicioM = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        tf_autorM = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        tf_calificacionM = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        fecha_CreacionM = new com.toedter.calendar.JDateChooser();
        jLabel48 = new javax.swing.JLabel();
        tf_EmpresaM = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabla_Servicio = new javax.swing.JTable();
        eliminar_Servicio = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        tf_nombreServicio = new javax.swing.JTextField();
        tf_precioServicio = new javax.swing.JTextField();
        tf_autor = new javax.swing.JTextField();
        tf_calificacion = new javax.swing.JTextField();
        tf_Empresa = new javax.swing.JTextField();
        agregar_Servicio = new javax.swing.JButton();
        fecha_Creacion = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel11 = new javax.swing.JPanel();
        cb_series = new javax.swing.JComboBox<>();
        modificar_Serie = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        tf_SerieNombreM = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        tf_SeriesTemporadasM = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        EstrenoSerieM = new com.toedter.calendar.JDateChooser();
        jLabel51 = new javax.swing.JLabel();
        tf_ActoresM = new javax.swing.JTextField();
        tf_RatingSeriesM = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_eliminarSerie = new javax.swing.JTable();
        eliminar_Series = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        tf_SerieNombre = new javax.swing.JTextField();
        tf_SeriesTemporadas = new javax.swing.JTextField();
        tf_RatingSeries = new javax.swing.JTextField();
        tf_Actores = new javax.swing.JTextField();
        agregar_Series = new javax.swing.JButton();
        EstrenoSerie = new com.toedter.calendar.JDateChooser();
        jPanel6 = new javax.swing.JPanel();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel13 = new javax.swing.JPanel();
        cb_Mini = new javax.swing.JComboBox<>();
        modificar_Mini = new javax.swing.JButton();
        jLabel43 = new javax.swing.JLabel();
        tf_MiniNombreM = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        tf_MiniTemporadasM = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        tf_MiniGeneroM = new javax.swing.JTextField();
        jLabel65 = new javax.swing.JLabel();
        tf_DuracionMiniM = new javax.swing.JTextField();
        jLabel66 = new javax.swing.JLabel();
        tf_descripMiniM = new javax.swing.JTextField();
        jPanel16 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tabla_eliminarMini = new javax.swing.JTable();
        eliminar_Mini = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        tf_MiniNombre = new javax.swing.JTextField();
        tf_MiniTemporadas = new javax.swing.JTextField();
        tf_MiniGenero = new javax.swing.JTextField();
        tf_descripMini = new javax.swing.JTextField();
        agregar_Mini = new javax.swing.JButton();
        tf_DuracionMini = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane6 = new javax.swing.JTabbedPane();
        jPanel18 = new javax.swing.JPanel();
        cb_pelicula = new javax.swing.JComboBox<>();
        modificar_Pelicula = new javax.swing.JButton();
        jLabel68 = new javax.swing.JLabel();
        tf_PeliculaNombre1 = new javax.swing.JTextField();
        jLabel69 = new javax.swing.JLabel();
        tf_PelisTemporadas1 = new javax.swing.JTextField();
        jLabel70 = new javax.swing.JLabel();
        tf_DuracionPelicula1 = new javax.swing.JTextField();
        jLabel71 = new javax.swing.JLabel();
        EstrenoCine1 = new com.toedter.calendar.JDateChooser();
        jLabel72 = new javax.swing.JLabel();
        EstrenoEnStream1 = new com.toedter.calendar.JDateChooser();
        jLabel73 = new javax.swing.JLabel();
        tf_plot1 = new javax.swing.JTextField();
        jPanel19 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tabla_eliminarPelicula = new javax.swing.JTable();
        eliminar_Pelicula = new javax.swing.JButton();
        jPanel20 = new javax.swing.JPanel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        tf_PeliculaNombre = new javax.swing.JTextField();
        tf_PelisTemporadas = new javax.swing.JTextField();
        tf_DuracionPelicula = new javax.swing.JTextField();
        tf_plot = new javax.swing.JTextField();
        agregar_Pelicula = new javax.swing.JButton();
        EstrenoCine = new com.toedter.calendar.JDateChooser();
        jLabel67 = new javax.swing.JLabel();
        EstrenoEnStream = new com.toedter.calendar.JDateChooser();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        user_login = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pass_login = new javax.swing.JTextField();
        login_button = new javax.swing.JButton();
        crear_CuentaBoton = new javax.swing.JButton();

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel3.setText("Crear Usuario");

        jLabel4.setText("Nombre");

        jLabel5.setText("Apellido");

        jLabel6.setText("Correo");

        jLabel7.setText("Numero");

        jLabel8.setText("Plan");

        jLabel9.setText("User");

        jLabel10.setText("Pass");

        buttonGroup1.add(Individual);
        Individual.setText("Individual");

        buttonGroup1.add(familiar);
        familiar.setText("Familiar");

        boton_CrearUsuario.setText("Crear");
        boton_CrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_CrearUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_CrearUsarioLayout = new javax.swing.GroupLayout(jd_CrearUsario.getContentPane());
        jd_CrearUsario.getContentPane().setLayout(jd_CrearUsarioLayout);
        jd_CrearUsarioLayout.setHorizontalGroup(
            jd_CrearUsarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CrearUsarioLayout.createSequentialGroup()
                .addGroup(jd_CrearUsarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_CrearUsarioLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(jd_CrearUsarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(jd_CrearUsarioLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jd_CrearUsarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addGroup(jd_CrearUsarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(boton_CrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jd_CrearUsarioLayout.createSequentialGroup()
                                            .addGroup(jd_CrearUsarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(jd_CrearUsarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel4)
                                                    .addComponent(jLabel5)
                                                    .addComponent(jLabel6)
                                                    .addComponent(jLabel7))
                                                .addGroup(jd_CrearUsarioLayout.createSequentialGroup()
                                                    .addComponent(jLabel8)
                                                    .addGap(26, 26, 26)))
                                            .addGroup(jd_CrearUsarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jd_CrearUsarioLayout.createSequentialGroup()
                                                    .addGap(127, 127, 127)
                                                    .addGroup(jd_CrearUsarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(tf_NumeroUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                                        .addComponent(tf_CorreoUsuario)
                                                        .addComponent(tf_ApellidoUsuario)
                                                        .addComponent(tf_nombreUsuario)))
                                                .addGroup(jd_CrearUsarioLayout.createSequentialGroup()
                                                    .addGap(115, 115, 115)
                                                    .addGroup(jd_CrearUsarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(Individual)
                                                        .addComponent(tf_Pass, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(tf_User, javax.swing.GroupLayout.Alignment.LEADING))
                                                    .addGap(39, 39, 39)
                                                    .addComponent(familiar)))))))))
                    .addGroup(jd_CrearUsarioLayout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(jLabel3)))
                .addContainerGap(214, Short.MAX_VALUE))
        );
        jd_CrearUsarioLayout.setVerticalGroup(
            jd_CrearUsarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CrearUsarioLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel3)
                .addGap(38, 38, 38)
                .addGroup(jd_CrearUsarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_nombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_CrearUsarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_ApellidoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_CrearUsarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(tf_CorreoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_CrearUsarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(tf_NumeroUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jd_CrearUsarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Individual)
                    .addComponent(familiar)
                    .addComponent(jLabel8))
                .addGap(28, 28, 28)
                .addGroup(jd_CrearUsarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tf_User, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jd_CrearUsarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tf_Pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(boton_CrearUsuario)
                .addGap(109, 109, 109))
        );

        cb_servicio.setMaximumRowCount(100);
        cb_servicio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_servicioItemStateChanged(evt);
            }
        });

        modificar_Usuario.setText("Modificar");
        modificar_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificar_UsuarioActionPerformed(evt);
            }
        });

        jLabel14.setText("Nombre");

        jLabel16.setText("Precio");

        jLabel17.setText("Autor:");

        jLabel46.setText("Calificacion");

        jLabel47.setText("Fecha de Creacion");

        jLabel48.setText("Empresa");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addComponent(modificar_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel46)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel48)
                                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel16)
                                        .addComponent(jLabel14)))
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(tf_nombreServicioM)
                                                .addComponent(tf_precioServicioM)
                                                .addComponent(tf_autorM, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(tf_EmpresaM, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(tf_calificacionM, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel47)
                                .addGap(39, 39, 39)
                                .addComponent(fecha_CreacionM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(cb_servicio, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(331, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(cb_servicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tf_nombreServicioM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(tf_precioServicioM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(tf_autorM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel46)
                    .addComponent(tf_calificacionM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel47)
                    .addComponent(fecha_CreacionM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel48)
                    .addComponent(tf_EmpresaM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(modificar_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Modificar", jPanel8);

        tabla_Servicio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre"
            }
        ));
        jScrollPane3.setViewportView(tabla_Servicio);

        eliminar_Servicio.setText("Eliminar");
        eliminar_Servicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminar_ServicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(357, 357, 357)
                .addComponent(eliminar_Servicio, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(357, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(eliminar_Servicio, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        jTabbedPane3.addTab("Eliminar", jPanel9);

        jLabel11.setText("Nombre");

        jLabel12.setText("Precio");

        jLabel13.setText("Autor:");

        jLabel15.setText("Calificacion");

        jLabel18.setText("Empresa");

        jLabel19.setText("Fecha de Creacion");

        agregar_Servicio.setText("Agregar");
        agregar_Servicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_ServicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel13)
                            .addComponent(jLabel18)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel12)
                                .addComponent(jLabel11)))
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tf_nombreServicio)
                                        .addComponent(tf_precioServicio)
                                        .addComponent(tf_autor, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE))
                                    .addComponent(tf_Empresa, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGap(105, 105, 105)
                                        .addComponent(agregar_Servicio, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(tf_calificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel19)
                        .addGap(39, 39, 39)
                        .addComponent(fecha_Creacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(377, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tf_nombreServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tf_precioServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tf_autor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tf_calificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19)
                    .addComponent(fecha_Creacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(tf_Empresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addComponent(agregar_Servicio)
                .addGap(53, 53, 53))
        );

        jTabbedPane3.addTab("Agregar", jPanel7);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 838, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane3))
        );

        jTabbedPane2.addTab("Servicios", jPanel3);

        cb_series.setMaximumRowCount(100);
        cb_series.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_seriesItemStateChanged(evt);
            }
        });

        modificar_Serie.setText("Modificar");
        modificar_Serie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificar_SerieActionPerformed(evt);
            }
        });

        jLabel34.setText("Nombre");

        jLabel35.setText("Temporadas");

        jLabel49.setText("Calificaciones");

        jLabel50.setText("Estreno");

        jLabel51.setText("Cantidad de Actores");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(289, 289, 289)
                        .addComponent(cb_series, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(326, 326, 326)
                        .addComponent(modificar_Serie, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel51)
                            .addComponent(jLabel50)
                            .addComponent(jLabel49)
                            .addComponent(jLabel35)
                            .addComponent(jLabel34))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(EstrenoSerieM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_SerieNombreM)
                            .addComponent(tf_SeriesTemporadasM)
                            .addComponent(tf_ActoresM, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                            .addComponent(tf_RatingSeriesM))))
                .addContainerGap(229, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(cb_series, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(tf_SerieNombreM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(tf_SeriesTemporadasM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel49)
                    .addComponent(tf_RatingSeriesM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EstrenoSerieM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel50))
                .addGap(40, 40, 40)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel51)
                    .addComponent(tf_ActoresM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(modificar_Serie, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Modificar", jPanel11);

        tabla_eliminarSerie.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre"
            }
        ));
        jScrollPane2.setViewportView(tabla_eliminarSerie);

        eliminar_Series.setText("Eliminar");
        eliminar_Series.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminar_SeriesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 825, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(305, 305, 305)
                .addComponent(eliminar_Series, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(eliminar_Series, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        jTabbedPane4.addTab("Eliminar", jPanel12);

        jLabel29.setText("Nombre");

        jLabel30.setText("Temporadas");

        jLabel31.setText("Calificaciones");

        jLabel32.setText("Estreno");

        jLabel33.setText("Cantidad de Actores");

        agregar_Series.setText("Agregar");
        agregar_Series.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_SeriesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(agregar_Series, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel33)
                            .addComponent(jLabel32)
                            .addComponent(jLabel31)
                            .addComponent(jLabel30)
                            .addComponent(jLabel29))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EstrenoSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tf_SerieNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                                .addComponent(tf_SeriesTemporadas)
                                .addComponent(tf_RatingSeries)
                                .addComponent(tf_Actores)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(tf_SerieNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(tf_SeriesTemporadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(tf_RatingSeries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EstrenoSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32))
                .addGap(40, 40, 40)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(tf_Actores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(agregar_Series, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Agregar", jPanel10);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane4)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane4)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Series", jPanel4);

        cb_Mini.setMaximumRowCount(100);
        cb_Mini.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_MiniItemStateChanged(evt);
            }
        });

        modificar_Mini.setText("Modificar");
        modificar_Mini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificar_MiniActionPerformed(evt);
            }
        });

        jLabel43.setText("Nombre");

        jLabel44.setText("Temporadas");

        jLabel45.setText("Genero");

        jLabel65.setText("Duracion");

        jLabel66.setText("Descripcion");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(289, 289, 289)
                        .addComponent(cb_Mini, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(326, 326, 326)
                        .addComponent(modificar_Mini, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel66)
                            .addComponent(jLabel65)
                            .addComponent(jLabel45)
                            .addComponent(jLabel44)
                            .addComponent(jLabel43))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_MiniNombreM)
                            .addComponent(tf_MiniTemporadasM)
                            .addComponent(tf_MiniGeneroM)
                            .addComponent(tf_descripMiniM)
                            .addComponent(tf_DuracionMiniM, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(255, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(cb_Mini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(tf_MiniNombreM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(tf_MiniTemporadasM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45)
                    .addComponent(tf_MiniGeneroM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel65)
                    .addComponent(tf_DuracionMiniM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel66)
                    .addComponent(tf_descripMiniM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(modificar_Mini, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("Modificar", jPanel13);

        tabla_eliminarMini.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre"
            }
        ));
        jScrollPane6.setViewportView(tabla_eliminarMini);

        eliminar_Mini.setText("Eliminar");
        eliminar_Mini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminar_MiniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 825, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(eliminar_Mini, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(311, 311, 311))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(eliminar_Mini, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        jTabbedPane5.addTab("Eliminar", jPanel16);

        jLabel38.setText("Nombre");

        jLabel39.setText("Temporadas");

        jLabel40.setText("Genero");

        jLabel41.setText("Duracion");

        jLabel42.setText("Descripcion");

        agregar_Mini.setText("Agregar");
        agregar_Mini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_MiniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(agregar_Mini, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel42)
                            .addComponent(jLabel41)
                            .addComponent(jLabel40)
                            .addComponent(jLabel39)
                            .addComponent(jLabel38))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_MiniNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                            .addComponent(tf_MiniTemporadas)
                            .addComponent(tf_MiniGenero)
                            .addComponent(tf_descripMini)
                            .addComponent(tf_DuracionMini))))
                .addContainerGap(409, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(tf_MiniNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(tf_MiniTemporadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(tf_MiniGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel41)
                    .addComponent(tf_DuracionMini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(tf_descripMini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(agregar_Mini, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("Agregar", jPanel17);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane5)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane5)
                .addContainerGap())
        );

        jTabbedPane2.addTab("MiniSerie", jPanel6);

        cb_pelicula.setMaximumRowCount(100);
        cb_pelicula.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_peliculaItemStateChanged(evt);
            }
        });

        modificar_Pelicula.setText("Modificar");
        modificar_Pelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificar_PeliculaActionPerformed(evt);
            }
        });

        jLabel68.setText("Nombre");

        jLabel69.setText("Temporadas");

        jLabel70.setText("Duracion");

        jLabel71.setText("Estreno Cine");

        jLabel72.setText("Estreno Stream");

        jLabel73.setText("Plot");

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addGap(289, 289, 289)
                        .addComponent(cb_pelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addGap(326, 326, 326)
                        .addComponent(modificar_Pelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel73)
                            .addComponent(jLabel71)
                            .addComponent(jLabel70)
                            .addComponent(jLabel69)
                            .addComponent(jLabel68)
                            .addComponent(jLabel72))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EstrenoCine1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tf_PeliculaNombre1)
                                .addComponent(tf_PelisTemporadas1)
                                .addComponent(tf_DuracionPelicula1)
                                .addComponent(tf_plot1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(EstrenoEnStream1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(248, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(cb_pelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel68)
                    .addComponent(tf_PeliculaNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel69)
                    .addComponent(tf_PelisTemporadas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel70)
                    .addComponent(tf_DuracionPelicula1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EstrenoCine1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel71))
                .addGap(31, 31, 31)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel72)
                    .addComponent(EstrenoEnStream1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_plot1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel73))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modificar_Pelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jTabbedPane6.addTab("Modificar", jPanel18);

        tabla_eliminarPelicula.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre"
            }
        ));
        jScrollPane7.setViewportView(tabla_eliminarPelicula);

        eliminar_Pelicula.setText("Eliminar");
        eliminar_Pelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminar_PeliculaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 835, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(305, 305, 305)
                .addComponent(eliminar_Pelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(eliminar_Pelicula, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        jTabbedPane6.addTab("Eliminar", jPanel19);

        jLabel60.setText("Nombre");

        jLabel61.setText("Temporadas");

        jLabel62.setText("Duracion");

        jLabel63.setText("Estreno Cine");

        jLabel64.setText("Plot");

        agregar_Pelicula.setText("Agregar");
        agregar_Pelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_PeliculaActionPerformed(evt);
            }
        });

        jLabel67.setText("Estreno Stream");

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel64)
                            .addComponent(jLabel63)
                            .addComponent(jLabel62)
                            .addComponent(jLabel61)
                            .addComponent(jLabel60)
                            .addComponent(jLabel67))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EstrenoCine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tf_PeliculaNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                                .addComponent(tf_PelisTemporadas)
                                .addComponent(tf_DuracionPelicula)
                                .addComponent(tf_plot))
                            .addGroup(jPanel20Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(EstrenoEnStream, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(agregar_Pelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(402, Short.MAX_VALUE))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel60)
                    .addComponent(tf_PeliculaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel61)
                    .addComponent(tf_PelisTemporadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel62)
                    .addComponent(tf_DuracionPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EstrenoCine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel63))
                .addGap(31, 31, 31)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel67)
                    .addComponent(EstrenoEnStream, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_plot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel64))
                .addGap(63, 63, 63)
                .addComponent(agregar_Pelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );

        jTabbedPane6.addTab("Agregar", jPanel20);

        jTabbedPane1.addTab("", jTabbedPane6);

        jTabbedPane2.addTab("Pelicula", jTabbedPane1);

        javax.swing.GroupLayout jd_adminLayout = new javax.swing.GroupLayout(jd_admin.getContentPane());
        jd_admin.getContentPane().setLayout(jd_adminLayout);
        jd_adminLayout.setHorizontalGroup(
            jd_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_adminLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 853, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jd_adminLayout.setVerticalGroup(
            jd_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_adminLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Username:");

        jLabel2.setText("Password:");

        login_button.setText("Login");
        login_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_buttonActionPerformed(evt);
            }
        });

        crear_CuentaBoton.setText("Crear Cuenta");
        crear_CuentaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crear_CuentaBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(343, 343, 343)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(login_button, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                            .addComponent(crear_CuentaBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(55, 55, 55)
                                .addComponent(pass_login, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(user_login, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(user_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pass_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(login_button)
                .addGap(18, 18, 18)
                .addComponent(crear_CuentaBoton)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void login_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_buttonActionPerformed
        try {
            String username = user_login.getText();
            String password = pass_login.getText();
            if (username.equals("david") && password.equals("1234")) {
                jd_admin.setModal(true);
                jd_admin.pack();
                jd_admin.setLocationRelativeTo(this);
                jd_admin.setVisible(true);

            } else {
                JOptionPane.showMessageDialog(this, "** USUARIO INCORRECTO **");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "** OCURRIO UN ERROR **");
        }
    }//GEN-LAST:event_login_buttonActionPerformed

    private void boton_CrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_CrearUsuarioActionPerformed

        String nombre = tf_NumeroUsuario.getText();
        String apellido = tf_ApellidoUsuario.getText();
        String correo = tf_CorreoUsuario.getText();
        String numero = tf_nombreUsuario.getText();
        String plan = "";
        if (familiar.isSelected()) {
            plan.equals("Familiar");
        } else if (Individual.isSelected()) {
            plan.equals("Individual");
        }
        String user = tf_User.getText();
        String pass = tf_Pass.getText();

        tf_NumeroUsuario.setText("");
        tf_ApellidoUsuario.setText("");
        tf_CorreoUsuario.setText("");
        tf_nombreUsuario.setText("");
        tf_User.setText("");
        tf_Pass.setText("");

        usuario.add(new Usuarios(nombre, apellido, correo, numero, plan, user, pass));


    }//GEN-LAST:event_boton_CrearUsuarioActionPerformed

    private void crear_CuentaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crear_CuentaBotonActionPerformed

        jd_CrearUsario.setModal(true);
        jd_CrearUsario.pack();
        jd_CrearUsario.setLocationRelativeTo(this);
        jd_CrearUsario.setVisible(true);
    }//GEN-LAST:event_crear_CuentaBotonActionPerformed

    private void eliminar_SeriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminar_SeriesActionPerformed
        if (tabla_eliminarSerie.getSelectedRow() >= 0) {
            int po = tabla_eliminarSerie.getSelectedRow();
            Series x = serie.get(tabla_eliminarSerie.getSelectedRow());
            serie.remove(tabla_eliminarSerie.getSelectedRow());
            DefaultTableModel modelo = (DefaultTableModel) tabla_eliminarSerie.getModel();
            modelo.removeRow(tabla_eliminarSerie.getSelectedRow());
            tabla_eliminarSerie.setModel(modelo);
            DefaultComboBoxModel dc = (DefaultComboBoxModel) cb_series.getModel();
            dc.removeElementAt(po);
            cb_series.setModel(dc);
        }


    }//GEN-LAST:event_eliminar_SeriesActionPerformed

    private void modificar_SerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificar_SerieActionPerformed
        String nombre = tf_SerieNombreM.getText();
        int temporada = Integer.parseInt(tf_SeriesTemporadasM.getText());
        int calificaciones = Integer.parseInt(tf_RatingSeriesM.getText());
        Date estreno = EstrenoSerieM.getDate();
        int actores = Integer.parseInt(tf_ActoresM.getText());
        int po = cb_series.getSelectedIndex();

        serie.get(po).setNombre(nombre);
        serie.get(po).setTemporadas(temporada);
        serie.get(po).setCalificacion(calificaciones);
        serie.get(po).setEstreno(estreno);
        serie.get(po).setActores(actores);

        Object[] serie = {nombre};
        Series x = new Series(nombre, temporada, calificaciones, estreno, actores);
        DefaultTableModel modelo = (DefaultTableModel) tabla_eliminarSerie.getModel();
        modelo.insertRow(cb_series.getSelectedIndex(), serie);
        modelo.removeRow(cb_series.getSelectedIndex() + 1);
        tabla_eliminarSerie.setModel(modelo);

        DefaultComboBoxModel dc = (DefaultComboBoxModel) cb_series.getModel();
        dc.setSelectedItem(x);
        dc.insertElementAt(x, po);
        dc.removeElementAt(po + 1);
        cb_series.setModel(dc);


    }//GEN-LAST:event_modificar_SerieActionPerformed

    private void cb_seriesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_seriesItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_seriesItemStateChanged

    private void agregar_SeriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_SeriesActionPerformed
        String nombre = tf_SerieNombre.getText();
        int temporada = Integer.parseInt(tf_SeriesTemporadas.getText());
        int calificaciones = Integer.parseInt(tf_RatingSeries.getText());
        Date estreno = EstrenoSerie.getDate();
        int actores = Integer.parseInt(tf_Actores.getText());

        tf_SerieNombre.setText("");
        tf_SeriesTemporadas.setText("");
        tf_RatingSeries.setText("");
        tf_Actores.setText("");

        serie.add(new Series(nombre, temporada, calificaciones, estreno, actores));

        Object[] serie = {nombre};
        DefaultTableModel modelo = (DefaultTableModel) tabla_eliminarSerie.getModel();
        modelo.addRow(serie);
        tabla_eliminarSerie.setModel(modelo);
        ///////////
        Series x = new Series(nombre, temporada, calificaciones, estreno, actores);
        DefaultComboBoxModel dc = (DefaultComboBoxModel) cb_servicio.getModel();
        dc.addElement(x);
        cb_series.setModel(dc);

    }//GEN-LAST:event_agregar_SeriesActionPerformed

    private void agregar_ServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_ServicioActionPerformed
        String nombre = tf_nombreServicio.getText();
        int precio = Integer.parseInt(tf_precioServicio.getText());
        String calificaciones = tf_calificacion.getText();

        Date fecha = fecha_Creacion.getDate();
        String empresa = tf_Empresa.getText();

        tf_nombreServicio.setText("");
        tf_precioServicio.setText("");
        tf_calificacion.setText("");
        tf_Empresa.setText("");
        servicios.add(new Servicios(nombre, precio, calificaciones, fecha, empresa));
        Object[] servicio = {nombre};
        DefaultTableModel modelo = (DefaultTableModel) tabla_Servicio.getModel();
        modelo.addRow(servicio);
        tabla_Servicio.setModel(modelo);
        /////////
        Servicios x = new Servicios(nombre, precio, calificaciones, fecha, empresa);
        DefaultComboBoxModel dc = (DefaultComboBoxModel) cb_servicio.getModel();
        dc.addElement(x);
        cb_servicio.setModel(dc);


    }//GEN-LAST:event_agregar_ServicioActionPerformed

    private void eliminar_ServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminar_ServicioActionPerformed
        if (tabla_Servicio.getSelectedRow() >= 0) {
            int po = tabla_Servicio.getSelectedRow();
            Servicios x = servicios.get(tabla_Servicio.getSelectedRow());
            servicios.remove(tabla_Servicio.getSelectedRow());
            DefaultTableModel modelo = (DefaultTableModel) tabla_Servicio.getModel();
            modelo.removeRow(tabla_Servicio.getSelectedRow());
            tabla_Servicio.setModel(modelo);
            DefaultComboBoxModel dc = (DefaultComboBoxModel) cb_servicio.getModel();
            dc.removeElementAt(po);
            cb_servicio.setModel(dc);
        }


    }//GEN-LAST:event_eliminar_ServicioActionPerformed

    private void modificar_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificar_UsuarioActionPerformed
        String nombre = tf_nombreServicioM.getText();
        int precio = Integer.parseInt(tf_precioServicioM.getText());
        String calificaciones = tf_calificacionM.getText();

        Date fecha = fecha_CreacionM.getDate();
        String empresa = tf_EmpresaM.getText();
        int po = cb_servicio.getSelectedIndex();
        servicios.get(po).setNombre(nombre);
        servicios.get(po).setPrecio(precio);
        servicios.get(po).setCalificacion(calificaciones);
        servicios.get(po).setFecha(fecha);
        servicios.get(po).setEmpresa(empresa);

        Object[] servicio = {nombre};
        Servicios x = new Servicios(nombre, precio, calificaciones, fecha, empresa);
        DefaultTableModel modelo = (DefaultTableModel) tabla_Servicio.getModel();
        modelo.insertRow(cb_servicio.getSelectedIndex(), servicio);
        modelo.removeRow(cb_servicio.getSelectedIndex() + 1);
        tabla_Servicio.setModel(modelo);

        DefaultComboBoxModel dc = (DefaultComboBoxModel) cb_servicio.getModel();
        dc.setSelectedItem(x);
        dc.insertElementAt(x, po);
        dc.removeElementAt(po + 1);
        cb_servicio.setModel(dc);


    }//GEN-LAST:event_modificar_UsuarioActionPerformed

    private void cb_servicioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_servicioItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_servicioItemStateChanged

    private void cb_MiniItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_MiniItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_MiniItemStateChanged

    private void modificar_MiniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificar_MiniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modificar_MiniActionPerformed

    private void eliminar_MiniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminar_MiniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminar_MiniActionPerformed

    private void agregar_MiniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_MiniActionPerformed
        String nombre = tf_MiniNombre.getText();
        int tempo = Integer.parseInt(tf_MiniTemporadas.getText());
        String genero = tf_MiniGenero.getText();
        int dura = Integer.parseInt(tf_DuracionMini.getText());
        String descripcion = tf_descripMini.getText();

        tf_MiniNombre.setText("");
        tf_MiniTemporadas.setText("");
        tf_MiniGenero.setText("");
        tf_DuracionMini.setText("");
        tf_descripMini.setText("");

        mini.add(new Miniseries(nombre, tempo, genero, dura, descripcion));
        Object[] Mini = {nombre};
        DefaultTableModel modelo = (DefaultTableModel) tabla_eliminarMini.getModel();
        modelo.addRow(Mini);
        tabla_eliminarMini.setModel(modelo);
        ////////
        Miniseries x = new Miniseries(nombre, tempo, genero, dura, descripcion);
        DefaultComboBoxModel dc = (DefaultComboBoxModel) cb_Mini.getModel();
        dc.addElement(x);
        cb_Mini.setModel(dc);

    }//GEN-LAST:event_agregar_MiniActionPerformed

    private void agregar_PeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_PeliculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agregar_PeliculaActionPerformed

    private void eliminar_PeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminar_PeliculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminar_PeliculaActionPerformed

    private void modificar_PeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificar_PeliculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modificar_PeliculaActionPerformed

    private void cb_peliculaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_peliculaItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_peliculaItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOGIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser EstrenoCine;
    private com.toedter.calendar.JDateChooser EstrenoCine1;
    private com.toedter.calendar.JDateChooser EstrenoEnStream;
    private com.toedter.calendar.JDateChooser EstrenoEnStream1;
    private com.toedter.calendar.JDateChooser EstrenoSerie;
    private com.toedter.calendar.JDateChooser EstrenoSerieM;
    private javax.swing.JRadioButton Individual;
    private javax.swing.JButton agregar_Mini;
    private javax.swing.JButton agregar_Pelicula;
    private javax.swing.JButton agregar_Series;
    private javax.swing.JButton agregar_Servicio;
    private javax.swing.JButton boton_CrearUsuario;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cb_Mini;
    private javax.swing.JComboBox<String> cb_pelicula;
    private javax.swing.JComboBox<String> cb_series;
    private javax.swing.JComboBox<String> cb_servicio;
    private javax.swing.JButton crear_CuentaBoton;
    private javax.swing.JButton eliminar_Mini;
    private javax.swing.JButton eliminar_Pelicula;
    private javax.swing.JButton eliminar_Series;
    private javax.swing.JButton eliminar_Servicio;
    private javax.swing.JRadioButton familiar;
    private com.toedter.calendar.JDateChooser fecha_Creacion;
    private com.toedter.calendar.JDateChooser fecha_CreacionM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTabbedPane jTabbedPane6;
    private javax.swing.JDialog jd_CrearUsario;
    private javax.swing.JDialog jd_admin;
    private javax.swing.JButton login_button;
    private javax.swing.JButton modificar_Mini;
    private javax.swing.JButton modificar_Pelicula;
    private javax.swing.JButton modificar_Serie;
    private javax.swing.JButton modificar_Usuario;
    private javax.swing.JTextField pass_login;
    private javax.swing.JTable tabla_Servicio;
    private javax.swing.JTable tabla_eliminarMini;
    private javax.swing.JTable tabla_eliminarPelicula;
    private javax.swing.JTable tabla_eliminarSerie;
    private javax.swing.JTextField tf_Actores;
    private javax.swing.JTextField tf_ActoresM;
    private javax.swing.JTextField tf_ApellidoUsuario;
    private javax.swing.JTextField tf_CorreoUsuario;
    private javax.swing.JTextField tf_DuracionMini;
    private javax.swing.JTextField tf_DuracionMiniM;
    private javax.swing.JTextField tf_DuracionPelicula;
    private javax.swing.JTextField tf_DuracionPelicula1;
    private javax.swing.JTextField tf_Empresa;
    private javax.swing.JTextField tf_EmpresaM;
    private javax.swing.JTextField tf_MiniGenero;
    private javax.swing.JTextField tf_MiniGeneroM;
    private javax.swing.JTextField tf_MiniNombre;
    private javax.swing.JTextField tf_MiniNombreM;
    private javax.swing.JTextField tf_MiniTemporadas;
    private javax.swing.JTextField tf_MiniTemporadasM;
    private javax.swing.JTextField tf_NumeroUsuario;
    private javax.swing.JTextField tf_Pass;
    private javax.swing.JTextField tf_PeliculaNombre;
    private javax.swing.JTextField tf_PeliculaNombre1;
    private javax.swing.JTextField tf_PelisTemporadas;
    private javax.swing.JTextField tf_PelisTemporadas1;
    private javax.swing.JTextField tf_RatingSeries;
    private javax.swing.JTextField tf_RatingSeriesM;
    private javax.swing.JTextField tf_SerieNombre;
    private javax.swing.JTextField tf_SerieNombreM;
    private javax.swing.JTextField tf_SeriesTemporadas;
    private javax.swing.JTextField tf_SeriesTemporadasM;
    private javax.swing.JTextField tf_User;
    private javax.swing.JTextField tf_autor;
    private javax.swing.JTextField tf_autorM;
    private javax.swing.JTextField tf_calificacion;
    private javax.swing.JTextField tf_calificacionM;
    private javax.swing.JTextField tf_descripMini;
    private javax.swing.JTextField tf_descripMiniM;
    private javax.swing.JTextField tf_nombreServicio;
    private javax.swing.JTextField tf_nombreServicioM;
    private javax.swing.JTextField tf_nombreUsuario;
    private javax.swing.JTextField tf_plot;
    private javax.swing.JTextField tf_plot1;
    private javax.swing.JTextField tf_precioServicio;
    private javax.swing.JTextField tf_precioServicioM;
    private javax.swing.JTextField user_login;
    // End of variables declaration//GEN-END:variables
  ArrayList<Usuarios> usuario = new ArrayList();
    ArrayList<Servicios> servicios = new ArrayList();
    ArrayList<Series> serie = new ArrayList();
    ArrayList<Miniseries> mini = new ArrayList();

}
